import StyleDictionary from "style-dictionary";

const PREFIX = "ds";

// ---- Custom formats: typed token object for programmatic use --------------
const flatEntries = (dictionary, render) =>
  dictionary.allTokens
    .map((t) => render(t.path.join("."), t.value ?? t.$value))
    .join("\n");

StyleDictionary.registerFormat({
  name: "ds/js",
  format: ({ dictionary }) =>
    `// Generated by Style Dictionary. Do not edit.\n` +
    `export const tokens = {\n` +
    flatEntries(
      dictionary,
      (k, v) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`,
    ) +
    `\n};\n\nexport default tokens;\n`,
});

StyleDictionary.registerFormat({
  name: "ds/dts",
  format: ({ dictionary }) =>
    `// Generated by Style Dictionary. Do not edit.\n` +
    `export declare const tokens: {\n` +
    flatEntries(dictionary, (k) => `  ${JSON.stringify(k)}: string;`) +
    `\n};\nexport type TokenName = keyof typeof tokens;\nexport default tokens;\n`,
});

// ---- Build helpers --------------------------------------------------------
const onlySource = (token) => token.isSource;

function cssLayer({
  include = [],
  source,
  selector,
  destination,
  outputReferences = true,
}) {
  return {
    include,
    source,
    log: { verbosity: "default" },
    platforms: {
      css: {
        prefix: PREFIX,
        transformGroup: "css",
        buildPath: "dist/css/",
        files: [
          {
            destination,
            format: "css/variables",
            filter: include.length ? onlySource : undefined,
            options: { selector, outputReferences },
          },
        ],
      },
    },
  };
}

const PRIMITIVE = "tokens/primitive/**/*.json";
const SEMANTIC_LIGHT = "tokens/semantic/light.json";
const SEMANTIC_DARK = "tokens/semantic/dark.json";
const BRAND_ACME = "tokens/brand/acme.json";
const COMPONENT = "tokens/component/**/*.json";

const builds = [
  // Primitives → :root
  cssLayer({
    source: [PRIMITIVE],
    selector: ":root",
    destination: "variables.css",
    outputReferences: false,
  }),
  // Semantic light → [data-theme~="light"]
  cssLayer({
    include: [PRIMITIVE],
    source: [SEMANTIC_LIGHT],
    selector: '[data-theme~="light"]',
    destination: "theme-light.css",
  }),
  // Semantic dark → [data-theme~="dark"]
  cssLayer({
    include: [PRIMITIVE],
    source: [SEMANTIC_DARK],
    selector: '[data-theme~="dark"]',
    destination: "theme-dark.css",
  }),
  // Brand override → [data-brand="acme"]
  cssLayer({
    include: [PRIMITIVE],
    source: [BRAND_ACME],
    selector: '[data-brand="acme"]',
    destination: "brand-acme.css",
  }),
  // Component layer → :root (references resolve to semantic var names)
  cssLayer({
    include: [PRIMITIVE, SEMANTIC_LIGHT],
    source: [COMPONENT],
    selector: ":root",
    destination: "components.css",
  }),
];

for (const config of builds) {
  const sd = new StyleDictionary(config);
  await sd.buildAllPlatforms();
}

// ---- TS export (resolved values, light semantics as canonical) -----------
const tsBuild = new StyleDictionary({
  prefix: PREFIX,
  source: [PRIMITIVE, SEMANTIC_LIGHT, COMPONENT],
  log: { verbosity: "default" },
  platforms: {
    ts: {
      prefix: PREFIX,
      transformGroup: "js",
      buildPath: "dist/ts/",
      files: [
        { destination: "tokens.js", format: "ds/js" },
        { destination: "tokens.d.ts", format: "ds/dts" },
      ],
    },
  },
});
await tsBuild.buildAllPlatforms();

// ---- Barrel: index.css that imports every layer in cascade order ----------
import { writeFile } from "node:fs/promises";
await writeFile(
  "dist/css/index.css",
  [
    '@import "./variables.css";',
    '@import "./theme-light.css";',
    '@import "./theme-dark.css";',
    '@import "./brand-acme.css";',
    '@import "./components.css";',
    "",
  ].join("\n"),
);

console.log("✓ Tokens built");
